version: '3'

networks:
  kitchhub:
    driver: bridge

services:
  # Backend
  webapi:
    build:
      context: .
      dockerfile: ./webapi/Dockerfile
    environment:
      - ASPNETCORE_URLS=https://+:5192;
      - SQLITE_PATH=/home/User/KitchHubDB.db
    networks:
      - kitchhub
    #volumes:
    #  - ~/home/User/KitchHubDB.db

  # Frontend
  vueclient:
    build: vueclient
    environment:
      - BASE_URLS=https://+:5192;
    ports:
      - 5192:80
    networks:
      - kitchhub